coverage:
  precision: 2
  round: down
  range: 90...100

  status:
    project:
      default:
        target: auto
        if_not_found: success
    patch: true
    changes: false

comment:
  layout: "header, diff"
  behavior: default